-- ============================================================
-- voidpros — real catalog batch 3: full 126-item list
-- Colors are assigned by rarity tier (not per-item) so the picker
-- visually communicates rarity at a glance: gray=Common, blue=Rare,
-- violet=Epic, gold=Legendary, pink=Uber. Icons cycle within each
-- category purely for visual variety — they're abstract, not literal.
-- Any name that already exists (a few overlap with earlier batches)
-- is skipped automatically via ON CONFLICT.
-- ============================================================

insert into items (id, name, type, icon, color, rarity) values
  -- ---------- HATS (55) ----------
  ('vih001', 'Adventure Buddy Hat', 'hat', 'crown', '#F0A8C9', 'Uber'),
  ('vih002', 'Laser Chicken Hat', 'hat', 'feather', '#F0A8C9', 'Uber'),
  ('vih003', 'Lonely Hat', 'hat', 'lamp', '#F0A8C9', 'Uber'),
  ('vih004', 'Felt Fedora', 'hat', 'wind', '#F0DDA6', 'Legendary'),
  ('vih005', 'Titanium Tiara', 'hat', 'crown', '#F0DDA6', 'Legendary'),
  ('vih006', 'Silk Top Hat', 'hat', 'feather', '#F0DDA6', 'Legendary'),
  ('vih007', 'Cake Hat', 'hat', 'lamp', '#F0DDA6', 'Legendary'),
  ('vih008', 'Floral Crochet Hat', 'hat', 'wind', '#F0DDA6', 'Legendary'),
  ('vih009', 'Wizard Hat', 'hat', 'crown', '#F0DDA6', 'Legendary'),
  ('vih010', 'Golden Halo', 'hat', 'feather', '#F0DDA6', 'Legendary'),
  ('vih011', 'Red Horns', 'hat', 'lamp', '#F0DDA6', 'Legendary'),
  ('vih012', 'Unicorn Horn', 'hat', 'wind', '#F0DDA6', 'Legendary'),
  ('vih013', 'Rainbow Party Hat', 'hat', 'crown', '#F0DDA6', 'Legendary'),
  ('vih014', 'Bejeweled Cowboy Hat', 'hat', 'feather', '#F0DDA6', 'Legendary'),
  ('vih015', 'Pirate Hat', 'hat', 'lamp', '#F0DDA6', 'Legendary'),
  ('vih016', 'Ice Cream Hat', 'hat', 'wind', '#F0DDA6', 'Legendary'),
  ('vih017', 'Pinwheel Hat', 'hat', 'crown', '#F0DDA6', 'Legendary'),
  ('vih018', 'Pearl Cloche Hat', 'hat', 'feather', '#F0DDA6', 'Legendary'),
  ('vih019', 'Construction Hat', 'hat', 'lamp', '#F0DDA6', 'Legendary'),
  ('vih020', 'Squid Hat', 'hat', 'wind', '#F0DDA6', 'Legendary'),
  ('vih021', 'Viking Hat', 'hat', 'crown', '#F0DDA6', 'Legendary'),
  ('vih022', 'Jester Hat', 'hat', 'feather', '#F0DDA6', 'Legendary'),
  ('vih023', 'Frog Hat', 'hat', 'lamp', '#F0DDA6', 'Legendary'),
  ('vih024', 'Turtle Hat', 'hat', 'wind', '#F0DDA6', 'Legendary'),
  ('vih025', 'Angler Hat', 'hat', 'crown', '#F0DDA6', 'Legendary'),
  ('vih026', 'Icy Tiara', 'hat', 'feather', '#F0DDA6', 'Legendary'),
  ('vih027', 'Chef Hat', 'hat', 'lamp', '#F0DDA6', 'Legendary'),
  ('vih028', 'Special Top Hat', 'hat', 'wind', '#F0DDA6', 'Legendary'),
  ('vih029', 'Karen Hair', 'hat', 'crown', '#F0DDA6', 'Legendary'),
  ('vih030', 'Plunger Hat', 'hat', 'feather', '#F0DDA6', 'Legendary'),
  ('vih031', 'Top Hat', 'hat', 'lamp', '#D9CDF0', 'Epic'),
  ('vih032', 'Cowboy Hat', 'hat', 'wind', '#D9CDF0', 'Epic'),
  ('vih033', 'Coral Sun Hat', 'hat', 'crown', '#D9CDF0', 'Epic'),
  ('vih034', 'Yellow Palm Cap', 'hat', 'feather', '#D9CDF0', 'Epic'),
  ('vih035', 'Blue Palm Cap', 'hat', 'lamp', '#D9CDF0', 'Epic'),
  ('vih036', 'Hibiscus Flower', 'hat', 'wind', '#D9CDF0', 'Epic'),
  ('vih037', 'Peony Wreath', 'hat', 'crown', '#D9CDF0', 'Epic'),
  ('vih038', 'Spider Hat', 'hat', 'feather', '#D9CDF0', 'Epic'),
  ('vih039', 'Purple Beanie', 'hat', 'lamp', '#D9CDF0', 'Epic'),
  ('vih040', 'Red Hat', 'hat', 'wind', '#D9CDF0', 'Epic'),
  ('vih041', 'Shitake Mushroom', 'hat', 'crown', '#CFE0EF', 'Rare'),
  ('vih042', 'Bee Antennae', 'hat', 'feather', '#CFE0EF', 'Rare'),
  ('vih043', 'Bat Headband', 'hat', 'lamp', '#CFE0EF', 'Rare'),
  ('vih044', 'Ruby Hair Bow', 'hat', 'wind', '#CFE0EF', 'Rare'),
  ('vih045', 'Death Cap Mushroom', 'hat', 'crown', '#CFE0EF', 'Rare'),
  ('vih046', 'Baseball Cap', 'hat', 'feather', '#CFE0EF', 'Rare'),
  ('vih047', 'Backwards Cap', 'hat', 'lamp', '#CFE0EF', 'Rare'),
  ('vih048', 'Beige Beret', 'hat', 'wind', '#CFE0EF', 'Rare'),
  ('vih049', 'Cherry Blossom Crown', 'hat', 'crown', '#CFE0EF', 'Rare'),
  ('vih050', 'Tropical Wreath', 'hat', 'feather', '#CFE0EF', 'Rare'),
  ('vih051', 'Leaf', 'hat', 'lamp', '#DCD6C9', 'Common'),
  ('vih052', 'Cosmos Flower', 'hat', 'wind', '#DCD6C9', 'Common'),
  ('vih053', 'Pink Dandelion', 'hat', 'crown', '#DCD6C9', 'Common'),
  ('vih054', 'Dandelion', 'hat', 'feather', '#DCD6C9', 'Common'),
  ('vih055', 'Amanita Mushroom', 'hat', 'lamp', '#DCD6C9', 'Common'),

  -- ---------- SCARVES (55) ----------
  ('vis001', 'Doge Scarf', 'scarf', 'bell', '#F0A8C9', 'Uber'),
  ('vis002', 'Alkaline Estrangement Scarf', 'scarf', 'wind', '#F0A8C9', 'Uber'),
  ('vis003', 'Parasite Scarf', 'scarf', 'sprout', '#F0A8C9', 'Uber'),
  ('vis004', 'Ruby Collar', 'scarf', 'gem', '#F0DDA6', 'Legendary'),
  ('vis005', 'Sorrow Scarf', 'scarf', 'bell', '#F0DDA6', 'Legendary'),
  ('vis006', 'Anxiety Scarf', 'scarf', 'wind', '#F0DDA6', 'Legendary'),
  ('vis007', 'Angry Scarf', 'scarf', 'sprout', '#F0DDA6', 'Legendary'),
  ('vis008', 'Envious Scarf', 'scarf', 'gem', '#F0DDA6', 'Legendary'),
  ('vis009', 'Cake Scarf', 'scarf', 'bell', '#F0DDA6', 'Legendary'),
  ('vis010', 'Paisley Cowboy Scarf', 'scarf', 'wind', '#F0DDA6', 'Legendary'),
  ('vis011', 'Checkered Scarf', 'scarf', 'sprout', '#F0DDA6', 'Legendary'),
  ('vis012', 'Bejeweled Pink Scarf', 'scarf', 'gem', '#F0DDA6', 'Legendary'),
  ('vis013', 'Mermaid Scarf', 'scarf', 'bell', '#F0DDA6', 'Legendary'),
  ('vis014', 'Watermelon Spiked Collar', 'scarf', 'wind', '#F0DDA6', 'Legendary'),
  ('vis015', 'Lemon Dolphin Float', 'scarf', 'sprout', '#F0DDA6', 'Legendary'),
  ('vis016', 'Serpent Scarf', 'scarf', 'gem', '#F0DDA6', 'Legendary'),
  ('vis017', 'Spider Necklace', 'scarf', 'bell', '#F0DDA6', 'Legendary'),
  ('vis018', 'Bubblegum Scarf', 'scarf', 'wind', '#F0DDA6', 'Legendary'),
  ('vis019', 'Jellyfish Scarf', 'scarf', 'sprout', '#F0DDA6', 'Legendary'),
  ('vis020', 'Prince''s Collar', 'scarf', 'gem', '#F0DDA6', 'Legendary'),
  ('vis021', 'Rubber Ring Donut', 'scarf', 'bell', '#F0DDA6', 'Legendary'),
  ('vis022', 'Wizard Cape', 'scarf', 'wind', '#F0DDA6', 'Legendary'),
  ('vis023', 'Blue Tie', 'scarf', 'sprout', '#F0DDA6', 'Legendary'),
  ('vis024', 'Fluffy Bunny', 'scarf', 'gem', '#F0DDA6', 'Legendary'),
  ('vis025', 'Ghostly Scarf', 'scarf', 'bell', '#F0DDA6', 'Legendary'),
  ('vis026', 'Black Cat Scarf', 'scarf', 'wind', '#F0DDA6', 'Legendary'),
  ('vis027', 'Equilibrium Scarf', 'scarf', 'sprout', '#F0DDA6', 'Legendary'),
  ('vis028', 'Focus Scarf', 'scarf', 'gem', '#F0DDA6', 'Legendary'),
  ('vis029', 'Golden Rabbit Scarf', 'scarf', 'bell', '#F0DDA6', 'Legendary'),
  ('vis030', 'Buster Scarf', 'scarf', 'wind', '#F0DDA6', 'Legendary'),
  ('vis031', 'Chunky Knit Scarf', 'scarf', 'sprout', '#D9CDF0', 'Epic'),
  ('vis032', 'Fall Camel Scarf', 'scarf', 'gem', '#D9CDF0', 'Epic'),
  ('vis033', 'Warm Pink Scarf', 'scarf', 'bell', '#D9CDF0', 'Epic'),
  ('vis034', 'Cowboy Scarf', 'scarf', 'wind', '#D9CDF0', 'Epic'),
  ('vis035', 'Aqua Spiked Collar', 'scarf', 'sprout', '#D9CDF0', 'Epic'),
  ('vis036', 'Hibiscus Chain', 'scarf', 'gem', '#D9CDF0', 'Epic'),
  ('vis037', 'Orange Butterfly Chain', 'scarf', 'bell', '#D9CDF0', 'Epic'),
  ('vis038', 'Gold Diamond Necklace', 'scarf', 'wind', '#D9CDF0', 'Epic'),
  ('vis039', 'Black Spiked Collar', 'scarf', 'sprout', '#D9CDF0', 'Epic'),
  ('vis040', 'Pink Spiked Collar', 'scarf', 'gem', '#D9CDF0', 'Epic'),
  ('vis041', 'Diamond Collar', 'scarf', 'bell', '#CFE0EF', 'Rare'),
  ('vis042', 'Red Ribbon Scarf', 'scarf', 'wind', '#CFE0EF', 'Rare'),
  ('vis043', 'Blue Ribbon Scarf', 'scarf', 'sprout', '#CFE0EF', 'Rare'),
  ('vis044', 'Yellow Ribbon Scarf', 'scarf', 'gem', '#CFE0EF', 'Rare'),
  ('vis045', 'Green Ribbon Scarf', 'scarf', 'bell', '#CFE0EF', 'Rare'),
  ('vis046', 'Lavender Ribbon Scarf', 'scarf', 'wind', '#CFE0EF', 'Rare'),
  ('vis047', 'Sea Dolphin Float', 'scarf', 'sprout', '#CFE0EF', 'Rare'),
  ('vis048', 'Blue Butterfly Chain', 'scarf', 'gem', '#CFE0EF', 'Rare'),
  ('vis049', 'Platinum Diamond Necklace', 'scarf', 'bell', '#CFE0EF', 'Rare'),
  ('vis050', 'Maroon Ribbon Scarf', 'scarf', 'wind', '#CFE0EF', 'Rare'),
  ('vis051', 'Retro Pink Flower Collar', 'scarf', 'sprout', '#DCD6C9', 'Common'),
  ('vis052', 'Red Bow Tie', 'scarf', 'gem', '#DCD6C9', 'Common'),
  ('vis053', 'Peach Dolphin Float', 'scarf', 'bell', '#DCD6C9', 'Common'),
  ('vis054', 'Turquoise Heart Collar', 'scarf', 'wind', '#DCD6C9', 'Common'),
  ('vis055', 'Daisy Chain', 'scarf', 'sprout', '#DCD6C9', 'Common'),

  -- ---------- TRINKETS / accessories (16) ----------
  ('via001', 'Stress Ball', 'accessory', 'testtube', '#D9CDF0', 'Epic'),
  ('via002', 'Fuzzy Mittens', 'accessory', 'coins', '#D9CDF0', 'Epic'),
  ('via003', 'Espresso Shot', 'accessory', 'flame', '#D9CDF0', 'Epic'),
  ('via004', 'Fluffy Pillow', 'accessory', 'gem', '#D9CDF0', 'Epic'),
  ('via005', 'Soft Dumbbell', 'accessory', 'testtube', '#D9CDF0', 'Epic'),
  ('via006', 'Gua Sha', 'accessory', 'coins', '#D9CDF0', 'Epic'),
  ('via007', 'Peppermint Tea', 'accessory', 'flame', '#D9CDF0', 'Epic'),
  ('via008', 'Skinny Vanilla Latte', 'accessory', 'gem', '#D9CDF0', 'Epic'),
  ('via009', 'Nail Buffers', 'accessory', 'testtube', '#CFE0EF', 'Rare'),
  ('via010', 'Leather Journal', 'accessory', 'coins', '#CFE0EF', 'Rare'),
  ('via011', 'Lychee Candle', 'accessory', 'flame', '#CFE0EF', 'Rare'),
  ('via012', 'Yoga Mat', 'accessory', 'gem', '#CFE0EF', 'Rare'),
  ('via013', 'Weighted Blanket', 'accessory', 'testtube', '#CFE0EF', 'Rare'),
  ('via014', 'Iced Coffee', 'accessory', 'coins', '#CFE0EF', 'Rare'),
  ('via015', 'Insulated Mug', 'accessory', 'flame', '#CFE0EF', 'Rare'),
  ('via016', 'Matcha Latte', 'accessory', 'gem', '#CFE0EF', 'Rare')
on conflict (name) do nothing;
